### ISSUE TITLE
[Bug] Channeling spells cancel immediately on clients with bad connection

### ISSUE THREAD

**Issue by moonsky70** [iron431/Irons-Spells-n-Spellbooks#243]
### Observed behaviour

In the event that any server-client with bad connection attempts to use a channeled spell, the spell will very quickly cancel, as though the player has stopped channeling. This is regardless of remaining cast time or mana.

### Expected behaviour

Channeled spells continue to cast for as long as the player has remaining cast-time and mana. 

### Steps to reproduce

1. Gain or emulate high ping, etc
2. Attempt to continually cast a channeled spell, e.g. Fire Breath or Dragon's Breath
3. The spell will briefly cast, then cancel

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.19.2-2.0.3

### Forge version

1.19.2-43.3.0

**Comment by MarioSMB** [comment]
Additionally to this effect if you swap spells and try to cast it quickly enough it will fail for a similar reason - the spellbook isn't keeping up with the client's actions on the server side.

**Comment by SpottyTheTurtle** [comment]
I have this issue consistently at 180ish ping, any luck on getting this fixed at some point?

**Comment by MarioSMB** [comment]
Ping. This still happens in latest versions, but mostly only with a staff - it will instantly cancel and put the spell on cooldown.

**Comment by Feldor-Lex** [comment]
Also getting this problem - quite difficult to work around this when you live abroad and have to host a server in the US.

**Comment by Feldor-Lex** [comment]
After a bit of testing, Long Cast spells work just fine - is it possible to change the backend of channeled spells to make them closer to Long Cast spells? Only stopping if the player runs out of mana or such? Perhaps a client config option players with bad ping can turn on which makes it so that channeled spells only get interrupted if you press the "cast" button a second time?

**Comment by NoodleRev** [comment]
I’ve had this occur while holding a spell book or staff and channeling the spell with right click. However I’ve found that binding a key to cast spells negates the issue for whatever reason.

**Comment by iron431** [comment]
closing for lack of version support
